version: "3.8"
services:
  appconfig:
    image: public.ecr.aws/aws-appconfig/aws-appconfig-agent:2.x
    environment:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ~/.aws:/root/.aws:ro
    ports:
      - "2772:2772"   # so you can curl it from your host too

  resizer:
    image: resizer:v1
    network_mode: "service:appconfig"
    environment:
      # tell the worker where the agent is
      APPCONFIG_APPLICATION: images-app
      APPCONFIG_ENVIRONMENT: dev
      APPCONFIG_PROFILE: resizer
    depends_on:
      - appconfig
    command: >
      sh -lc '
        echo "Waiting for AppConfig agent on localhost:2772..." ;
        until curl -sf http://localhost:2772/ >/dev/null 2>&1 ; do
          sleep 0.5 ;
        done ;
        echo "Agent is up; starting worker" ;
        python -u app.py
      '
    volumes:
      - ~/.aws:/root/.aws:ro